Insert metatada in json reporter
DevExpress/testcafe-reporter-json pull request #4
Opened 2019-05-29 17:02 UTC by FpereraMaia

I need the metadata in json, maybe its interesting put this inside your package. :)

2019-06-03 11:02 UTC, AndreyBelym requested changes
Thank you for your contribution. There are some very minor flaws. but we will work them out :smile:. And don't you mind modify [.travis.yml](https://github.com/DevExpress/testcafe-reporter-json/blob/master/.travis.yml) to run tests on Node 8, 10, and stable instead of the current configuration, and specify `"engines": { "node": ">=8.0.0" }` in `package.json`?,

2019-06-03 11:02 UTC, AndreyBelym commented on package-lock.json
> +{
Please add `package-lock.json` to `.gitignore`. Since this plugin is installed as a dependency, it will be ignored by `npm` anyway.

2019-06-03 11:02 UTC, AndreyBelym commented on package.json
> +    "testcafe-reporter-json-complete": "^2.1.1"
I guess you used it for debugging purposes, could you please remove it?

2019-06-03 11:02 UTC, AndreyBelym commented on src/index.js
> +        reportTestDone (name, testRunInfo, meta) {
The `reportFixtureStart` method specifies the fixture metadata: https://devexpress.github.io/testcafe/documentation/extending-testcafe/reporter-plugin/reporter-methods.html#reportfixturestart. I think we should handle it too.

2019-06-03 14:29 UTC, FpereraMaia commented
@AndreyBelym at stable node version: 12.3.1 we have an issue, how you can see in https://travis-ci.org/DevExpress/testcafe-reporter-json/jobs/540771953

With a fastly search the "people on internet" says this issue is a problem with gulp support. But... with a install gulp > 4.0.0 we broke the things in project. Can you help me with the best solution for this?

2019-06-25 09:11 UTC, merged

2019-06-25 12:56 UTC, FpereraMaia commented
Thanks @AndreyBelym